import { LeaderboardEntry } from "./types";

export const mockLeaderboard: LeaderboardEntry[] = [
    {
      rank: 1,
      playerAddress: "0x1234...5678",
      characterName: "Shadowbane",
      characterClass: "Necromancer",
      rarity: "Legendary",
      totalPower: 847,
      topStat: "Intelligence",
      topStatValue: 198,
      avatar: "/legendary-necromancer.png",
    },
    {
      rank: 2,
      playerAddress: "0xabcd...efgh",
      characterName: "Stormcaller",
      characterClass: "Mage",
      rarity: "Legendary",
      totalPower: 832,
      topStat: "Intelligence",
      topStatValue: 195,
      avatar: "/legendary-mage.png",
    },
    {
      rank: 3,
      playerAddress: "0x9876...4321",
      characterName: "Ironheart",
      characterClass: "Warrior",
      rarity: "Epic",
      totalPower: 789,
      topStat: "Strength",
      topStatValue: 187,
      avatar: "/epic-warrior.png",
    },
    {
      rank: 4,
      playerAddress: "0xdef0...1234",
      characterName: "Moonwhisper",
      characterClass: "Archer",
      rarity: "Epic",
      totalPower: 756,
      topStat: "Agility",
      topStatValue: 179,
      avatar: "/placeholder-tlznw.png",
    },
    {
      rank: 5,
      playerAddress: "0x5678...9abc",
      characterName: "Flamestrike",
      characterClass: "Paladin",
      rarity: "Epic",
      totalPower: 743,
      topStat: "Strength",
      topStatValue: 176,
      avatar: "/epic-paladin.png",
    },
    {
      rank: 6,
      playerAddress: "0x2468...1357",
      characterName: "Frostborn",
      characterClass: "Mage",
      rarity: "Rare",
      totalPower: 698,
      topStat: "Intelligence",
      topStatValue: 165,
      avatar: "/rare-mage.png",
    },
    {
      rank: 7,
      playerAddress: "0x1357...2468",
      characterName: "Voidwalker",
      characterClass: "Rogue",
      rarity: "Rare",
      totalPower: 672,
      topStat: "Agility",
      topStatValue: 158,
      avatar: "/rare-rogue.png",
    },
    {
      rank: 8,
      playerAddress: "0x8642...9753",
      characterName: "Lightbringer",
      characterClass: "Paladin",
      rarity: "Rare",
      totalPower: 645,
      topStat: "Vitality",
      topStatValue: 152,
      avatar: "/rare-paladin.png",
    },
  ]
